import pyautogui
import time
time.sleep(5)
x,y=pyautogui.position()
pyautogui.click(x,y)
time.sleep(2)
pyautogui.hotkey('ctrl','a')
time.sleep(2)
pyautogui.hotkey('ctrl','c')
#checking copy and past option
time.sleep(2)
pyautogui.press('win')
time.sleep(2)
pyautogui.typewrite('notepad')
time.sleep(2)
pyautogui.press('enter')
time.sleep(2)
pyautogui.hotkey('ctrl','v')
time.sleep(2)
pyautogui.hotkey('ctrl','s')
time.sleep(2)
pyautogui.typewrite('copy-paste.txt')
time.sleep(1)
pyautogui.press('enter')
